### ISSUE TITLE
After upgrading Prima ... other Prima-related modules break (error messages, segfault)

### ISSUE THREAD

**Issue by HaraldJoerg** [dk/Prima#116]
I am using Prima and OpenGL, and also Prima and PDL.  After upgrading Prima to 1.73, Prima::OpenGL and PDL::Graphics::Prima had strange errors, including occasional segfaults.  For both modules, re-installing the same version again (i.e. recompiling) fixed the issue.

Is there a way how I can find out which modules need to be re-installed after a Prima upgrade?  Or can Prima defend itself against binary incompatible modules?

**Comment by mohawk2** [comment]
I had a look at Prima's code, and in `include/apricot.h` there's a `PRIMA_VERSION_BOOTCHECK` which does such a defence already. The version it checks against, `PRIMA_CORE_VERSION `, in latest `master`, is `2017050901`. Please can this get updated when ABI gets broken, so that users will actually know?

**Comment by dk** [comment]
Yes of course. I am consistently forgetting this
