### ISSUE TITLE
Install Issue - Font Tests Failing

### ISSUE THREAD

**Issue by ArcanaCorvus** [dk/Prima#99]
Hello I was trying to install Prima today on my OpenSuse Tumbleweed machine and it seems mostly okay except for the failure of a few font related tests. I've attached the output as an image and I've looked around a bit but I can't seem to figure out what is going wrong.

![image](https://github.com/dk/Prima/assets/11635065/7c58a0eb-6ba5-44dc-a8d1-b03f3c02f5ce)

**Comment by dk** [comment]
Hi these tests dont't really show a bug but rather a buggy or a very special font installed. So after many people complained on this I finally renamed Font.t to Font.xt so that it doesn't get executed on make test. (It still doesn on make xtest though).

Anyway. From this point you can safely disregard that failure and install Prima anyway, or fetch the latest git snapshot and check if all tests pass.

**Comment by ArcanaCorvus** [comment]
Thanks for the help!
